image: node:0.12.7

stages:
  - build

before_script:
  - npm install -g grunt
  - npm install -g mocha

build:
  stage: build
  script: 
    - npm install
  only: master
  tags:
    - snapbook
    - api
    - gateway
