image: node:0.12.7

stages:
  - build
  - test

before_script:
  - npm install -g grunt

job_build:
  stage: build
  script: "npm install"
  only: master
  tags:
    - snapbook
    - api
    - gateway

job_test:
  stage: test
  script: "npm test"
  only: master
  tags:
    - snapbook
    - api
    - gateway
