image: node:0.12.7

before_script:
  - node --version
  - npm install -g mocha
  - npm install -g grunt-cli
  - npm install

stages:
  - test
  - deploy

job_test:
  type: test
  script: npm test
    - git push --force --yes git@github.com:gperreymond/snapbook-api-gateway.git
  only:
    - master

job_deploy:
  type: deploy
  script: git push --force --yes git@github.com:gperreymond/snapbook-api-gateway.git
  only:
    - master
