image: node:0.12.7

stages:
  - build
  - test

job_build:
  stage: build
  before_script:
    - npm install -g grunt
  script:
    - npm install
  only: master
  tags:
    - snapbook
    - api
    - gateway

job_test:
  stage: test
  script:
    - npm test
  only: master
  tags:
    - snapbook
    - api
    - gateway
