language: node_js
sudo: false
node_js:
  - '0.12'

cache:
  directories:
    - node_modules

matrix:
  fast_finish: true
  allow_failures:
    - node_js: '0.12'

install:
  # Disable the spinner, it looks bad on Travis
  - npm config set spin false
  - npm install -g npm@latest

before_script:
  - npm install -g mocha
  - npm install -g grunt

script:
  - npm test