{
    "apps": [
        {
            "name" : "snapbook-api-gateway",
            "script" : "src/index.js",
            "watch" : false,
            "error_file": "/dsi/logs/snapbook-api-gateway.error",
            "out_file": "/dsi/logs/snapbook-api-gateway.log"
        }
    ]
}